### ISSUE TITLE
Abfrage via Intervallvorgabe ohne Funktion

### ISSUE THREAD

**Issue by shivan** [En3rGy/11081-Fritz-DECT200#1]
Hi,
ich hatte den Baustein eigentlich schonmal bei mir am Laufen. Aber aktuell geht da nichts mehr. Irgendwie hat Gira auch den Simulator in der aktuellen Schnittstellen-Doku entfernt.

Im Debugger bekomme ich nun auf der Debug-Seite:
File "Fritz DECT200 (11081)11081", line 422, in __thread_queue_consumer
File "Fritz DECT200 (11081)11081", line 660, in on_input_value
File "Fritz DECT200 (11081)11081", line 632, in trigger
File "Fritz DECT200 (11081)11081", line 551, in get_sid
NameError: global name 're' is not defined

Beim HomeServer (4.11) kommt bei mir aktuell garnichts.
Kann ich eigentlich irgendwie das Logging aktivieren, so dass ich auch auf dem Homeserver ein Log bekomme? Oder zumindest im Simulator.

Ich habe auch in der config.xml mittlerweile rausgefunden, dass
`<logging type="Syslog" />`

gesetzt werden kann - obwohl das im Simulator wohl sogar nicht mal notwendig ist.

**Comment by En3rGy** [comment]
Der Fehler mit

> NameError: global name 're' is not defined

spricht dafür, dass eine std. Python-Bibliothek nicht gefunden wird. Das ist schon sehr seltsam. Schau mal, ob das letzte Release funktioniert:
https://github.com/En3rGy/11081-Fritz-DECT200/releases/tag/v1.1

**Comment by shivan** [comment]
Habs gleich auf dem HS (4.11) probiert. Sieht gut aus. 
Nun kam eine Exception mit Connection refused. 
Dann habe ich den Port entfernt, so dass nur noch die IP drin steht, und jetzt wow kommen Daten!
Mal sehen wie lange es wieder funktioniert ;-)

DANKE

**Comment by shivan** [comment]
Wenn ich Intervall auf 60 setze, sollte er doch alle 60 Sek was abrufen oder?
Im Logik-Debugger tut sich aber nichts von alleine. Ich habe nun wieder einen Telegramm-Generator vorgeschaltet. Mal sehen obs dann geht...

**Comment by En3rGy** [comment]
Intervall-Bug gefunden. Ist in v1.2 gefixed: https://github.com/En3rGy/11081-Fritz-DECT200/releases/tag/v1.2

**Comment by shivan** [comment]
Danke. Gleich mal live im HS testen...

**Comment by shivan** [comment]
Also irgendwie triggert der trotzdem noch nicht... :-(

![image](https://user-images.githubusercontent.com/1827692/110908547-4593e300-830f-11eb-9883-3e0bca0109aa.png)

Verrat mir doch mal, wie ich das Logging für den Baustein im HS selbst aktivieren kann, vielleicht sieht man dort was.

**Comment by En3rGy** [comment]
Gibt keinen Weg, logging zu aktivieren. Der Baustein logged über die HS-Debug-Seite im Abschnitt HSL2.0.
Außerdem über die neue Funktion im Experten wie du's ja schon gemacht hast. 
Ich schaue es mir noch mal an...

**Comment by shivan** [comment]
Wenn ich von Hand den "Intervall" z.B. mit 61 im Überwachen-Modus setze, dann gehts los und es werden 1x Daten ermittelt.

Beim nächsten Update könntest du noch Intervall umbenennen, das sind ja Sekunden oder? in "Intervall (s)", dann ist es selbsterklärend.

**Comment by En3rGy** [comment]
[v1.3 ist online](https://github.com/En3rGy/11081-Fritz-DECT200/releases/tag/v1.3). Im Debug-Bereich sollte jetzt eine Msg. hochlaufen, wenn eine neue XML-Datei von der Fritzbox empfangen wurde. Da die Ausgänge SBC ausgeführt sind, muss nicht nach jedem abgelaufenen Intervall ein Ausgang geschrieben werden.

**Comment by shivan** [comment]
Mit v1.3:
Wenn ich dem Baustein "Starthilfe" gebe, d.h. nach dem Hochfahren einmal den "Intervall" setze, läuft er zyklisch los. D.h. nach dem Hochfahren scheint er nicht zu starten.

Auf der Debug-Seite steht nun:
14.03.2021 15:59:51 (49)
11081 Get XML result: 200

**Comment by En3rGy** [comment]
Das mit der Starthilfe war ein guter Hinweis. Neuer Fix in neuem Release: https://github.com/En3rGy/11081-Fritz-DECT200/releases/tag/v1.4

**Comment by shivan** [comment]
Leider auch mit 1.4 läuft der Baustein nach dem Hochfahren des Homeservers nicht automatisch los.
Gab es nicht so eine Option "Neuberechnen beim Start", das man beim Logikbaustein definieren muss, kann mich da dunkel erinnern, mal was drüber gelesen zu haben.

**Comment by En3rGy** [comment]
Ja hab's schon gesehen und behoben. Teste jetzt aber intensiver bei mir. Die Versionen schießen gerade ziemlich in die Höhe. Sieht aber bisher gut aus. Bisher 341 erfolgreiche Abfragen, ohne das der Baustein manuell getriggert wurde.

**Comment by En3rGy** [comment]
Neues release: https://github.com/En3rGy/11081-Fritz-DECT200/releases/tag/v1.5
(Neuer) Unit Test und System Test lassen vermuten, dass Bug behoben ist.

**Comment by shivan** [comment]
Hehe, hattest die PIN-Nr >0 geprüft, anstatt den eigentlichen Wert ;-)

Ich versuch nun die 1.5 bei mir... geb dir dann wieder Bescheid.

Achja, gibts bei dir eigentlich noch den Simulator im SDK?

**Comment by shivan** [comment]
Boah ich glaubs nicht... aber ich hab den Baustein nicht angefasst, aber er rennt los :-)

Na also, geschafft! 👍

**Comment by En3rGy** [comment]
Den Simulator gibts noch, schaue dir die Dateien 02 sim.cmd und 03 debug.cmd hier im repo an. Allerdings finde ich ihn nicht mehr in der Doku und der Syntax war etwas speziell. Daher nutze ich ihn nicht.

**Comment by shivan** [comment]
Verstehe ich es richtig, du hast dann somit "doppelt" implementiert. Einmal als Logikbaustein und die Logik nochmal in deinem Test-Fall?

Ich fand den Simulator bisher eigentlich ganz bequem. Einfach die Eingänge befüllen und loslaufen lassen. Aber mir ist eben aufgefallen, dass der Simulator nun weg ist. Debugging fehlt natürlich. 
PS: in deinem Test hast du noch hsl20_3 statt hsl20_4, aber ist ja eh nur deine Debug-Klasse.
