### ISSUE TITLE
Exception breaks XML processing

### ISSUE THREAD

**Issue by En3rGy** [En3rGy/11081-Fritz-DECT200#4]
Exception handling shall be installed for all values separately. Currently, on error for one value discards all values from one xml event.

**Comment by shivan** [comment]
Will this fix:


16.04.2021 17:02:43 (1)'[Errno http error] no host given' in get_sid()
16.04.2021 17:02:43 (1)11081 Could not receive valid SID
17.04.2021 09:50:14 (195)11081 Error processing XML, code:999

?

**Comment by En3rGy** [comment]
No,

the 1st two are caused by a missing network connection. E.g. during HS restart.
The 3rd one inidcates a wring SSID. There might be a bug here which I'm investigating opening https://github.com/En3rGy/11081-Fritz-DECT200/issues/5
